version: '3.8'

services:
  server:
    restart: always
    build:
      context: ./server
      dockerfile: ../config/development/Dockerfile.server
    volumes:
      - ./server:/app
      - /app/node_modules
    environment:
      - BASE_URL=http://localhost:3000
      - DATABASE_URL=postgres://postgres:logicenKanban@planka-2-secure.cbg6k6oea1qt.us-east-2.rds.amazonaws.com:5432/planka?ssl=true
      - SECRET_KEY=notsecretkey

      # - TRUST_PROXY=0
      # - TOKEN_EXPIRES_IN=365 # In days

      # related: https://github.com/knex/knex/issues/2354
      # As knex does not pass query parameters from the connection string we
      # have to use environment variables in order to pass the desired values, e.g.
      # - PGSSLMODE=<value>

      # Configure knex to accept SSL certificates
      - KNEX_REJECT_UNAUTHORIZED_SSL_CERTIFICATE=false

      - DEFAULT_ADMIN_EMAIL=demo@demo.demo # Do not remove if you want to prevent this user from being edited/deleted
      - DEFAULT_ADMIN_PASSWORD=demo
      - DEFAULT_ADMIN_NAME=Demo Demo
      - DEFAULT_ADMIN_USERNAME=demo

      # - SHOW_DETAILED_AUTH_ERRORS=false # Set to true to show more detailed authentication error messages. It should not be enabled without a rate limiter for security reasons.

      - ALLOW_ALL_TO_CREATE_PROJECTS=true

      - OIDC_ISSUER=https://dev-qzcvfh528fkp18qt.us.auth0.com/
      - OIDC_CLIENT_ID=Y6ALNb6RUHtitFH1fIvd3SZKq4dt0TE9
      - OIDC_CLIENT_SECRET=UVb3Oj2tZAoW7zqLl88MEpnN9YcJdumq8igvvBrsNv-qI_c5gP0eh2StwBCtar8m
      - OIDC_ID_TOKEN_SIGNED_RESPONSE_ALG=RS256
      - OIDC_USERINFO_SIGNED_RESPONSE_ALG=RS256
      - OIDC_SCOPES=openid email profile
      - OIDC_RESPONSE_MODE=fragment
      - OIDC_USE_DEFAULT_RESPONSE_MODE=true
      - OIDC_ADMIN_ROLES=admin
      - OIDC_CLAIMS_SOURCE=id_token
      - OIDC_EMAIL_ATTRIBUTE=email
      - OIDC_NAME_ATTRIBUTE=name
      - OIDC_USERNAME_ATTRIBUTE=preferred_username
      - OIDC_ROLES_ATTRIBUTE=groups
      - OIDC_IGNORE_USERNAME=true
      - OIDC_IGNORE_ROLES=true
      - OIDC_ENFORCED=true

      # Email Notifications (https://nodemailer.com/smtp/)
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=465
      - SMTP_SECURE=true
      - SMTP_USER=enrique@logicen.com.mx
      - SMTP_PASSWORD=esdl hzxv hzic dwhq
      - SMTP_FROM="Logicen Tracking" enrique@logicen.com.mx
      - SMTP_TLS_REJECT_UNAUTHORIZED=false
      # Optional fields: accessToken, events, excludedEvents
      # - |
      #   WEBHOOKS=[{
      #     "url": "http://localhost:3001",
      #     "accessToken": "notaccesstoken",
      #     "events": ["cardCreate", "cardUpdate", "cardDelete"],
      #     "excludedEvents": ["notificationCreate", "notificationUpdate"]
      #   }]

      # - SLACK_BOT_TOKEN=
      # - SLACK_CHANNEL_ID=

      # - GOOGLE_CHAT_WEBHOOK_URL=

      # - TELEGRAM_BOT_TOKEN=
      # - TELEGRAM_CHAT_ID=
      # - TELEGRAM_THREAD_ID=

      # Attachments S3
      # - S3_ENABLE=true
      # - S3_REGION=
      # - S3_ENDPOINT=
      # - S3_BUCKET=
      # - S3_ACCESS_KEY=
      # - S3_SECRET_KEY=
    working_dir: /app
    command: ["sh", "-c", "npm run start"]

  client:
    restart: always
    image: ghcr.io/plankanban/planka-client:local
    volumes:
      - ./client:/app/client
      - /app/client/node_modules
      - /app/node_modules
    environment:
      - DISABLE_ESLINT_PLUGIN=true
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - BASE_URL=http://localhost:3000
      - REACT_APP_SERVER_BASE_URL=http://localhost:3000
    working_dir: /app/client
    command: npm start

  proxy:
    restart: always
    image: nginx:alpine
    ports:
      - "3000:80"
    volumes:
      - ./config/development/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - server
      - client

volumes:
  db-data:
